### ISSUE TITLE
draft designation embeds a draft watermark

### ISSUE THREAD

**Issue by blueheadpublishing** [worlduniting/old-bookshop#13]
user should be able to designate that the book is a draft in +config/book.yml+
# config/book.yml

draft: yes

when +'bookshop build'+ is called and draft is designated as yes in +config/book.yml+ the build should embed a 'draft' png as a watermark.

example draft.png https://github.com/blueheadpublishing/catfood/blob/master/bookshop/draft.png

**Comment by davidandrewthompson** [comment]
I think this should be inserted into the specific stylesheet which conforms better to our best practices.
