### ISSUE TITLE
<nav epub:type="toc"> throws Prince error

### ISSUE THREAD

**Issue by davidandrewthompson** [worlduniting/old-bookshop#36]
When calling bookshop build pdf with <nav epub:type="toc"> as the table of contents nav structure (Epub3), the following error is throw.

```
prince: builds/html/book.html:34: error: Namespace prefix epub for type on nav is not defined
```

The pdf is still built, regardless of the error.

**Comment by davidandrewthompson** [comment]
This is something that will have to be fixed on PrinceXML's side. I will contact them and report the issue.

**Comment by blueheadpublishing** [comment]
issue reported to PrinceXML. Closing ticket until I hear back from them.
