### ISSUE TITLE
bookshop build not working on MacOS

### ISSUE THREAD

**Issue by blowback** [worlduniting/old-bookshop#54]
Anthonys-MacBook-Pro:tmp ant$ **bookshop new FooBook**
creating base project
      create  FooBook
      [lots more good stuff]
       chmod  FooBook/script/zip/zip.exe

Anthonys-MacBook-Pro:tmp ant$ **cd FooBook/**
Anthonys-MacBook-Pro:FooBook ant$ **bookshop build pdf**
script/bookshop:5 :in `require': no such file to load -- bookshop/commands (LoadError)
    from script/bookshop:5

Anthonys-MacBook-Pro:FooBook ant$ **gem environment**
RubyGems Environment:
- RUBYGEMS VERSION: 1.8.24
- RUBY VERSION: 1.8.7 (2011-12-28 patchlevel 357) [universal-darwin11.0]
- INSTALLATION DIRECTORY: /Library/Ruby/Gems/1.8
- RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
- EXECUTABLE DIRECTORY: /usr/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - universal-darwin-11
- GEM PATHS:
  - /Library/Ruby/Gems/1.8
  - /Users/ant/.gem/ruby/1.8
  - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/

**Comment by blowback** [comment]
That was system ruby. Switched to rvm 1.9.3-head, works fine.

**Comment by davidandrewthompson** [comment]
Thanks for reporting the issue. I created an issue #55 around this and am going to close this one.

Thanks again! And please let me know if you have any suggestions on creating a better bookshop! :-)
