### ISSUE TITLE
help text for 'bookshop new' not displaying correct help text

### ISSUE THREAD

**Issue by blueheadpublishing** [worlduniting/old-bookshop#7]
when user issues 'bookshop build new' from the command line from outside a bookshop project folder, it should return help text stating:

```
Options should be given after the application name. For details run: bookshop --help
```

currently when the user issues the above command, it returns

```
No value provided for required arguments 'app_path'
```

**Comment by EmilyVoukelatou** [comment]
Currently it outputs:

```
Usage:
  bookshop new APP_PATH [options]
```

Is this the desired behavior?

**Comment by blueheadpublishing** [comment]
Sorry, I did not accurately describe the problem in this issues.

when 'bookshop' by itself is issued, it correctly returns:

```
Usage:
  bookshop new APP_PATH [options]
```

however, when 'bookshop new' is issued, it returns:

```
No value provided for required arguments 'app_path'
```

I think I would like both of them to return:

```
Usage:
  bookshop new BOOK_NAME [options]
```

I think that APP_PATH may not make much sense to many users. Behaviorally, users will see that a new directory is created within the current directory. Whereas APP_PATH is technically more specific, it may just be too confusing for most users.

**Comment by EmilyVoukelatou** [comment]
I have given this issue a try (https://github.com/blueheadpublishing/bookshop/pull/42) but let's not close it before I write some cucumber scenarios for our expectations.

**Comment by davidandrewthompson** [comment]
I like the direction you are going with this. I agree... it will probably be easier to develop our own error handling rather than hacking Thor.

Let's try and develop some Cucumber tests for this commit.

**Comment by EmilyVoukelatou** [comment]
I think we can close the issue now :)

**Comment by davidandrewthompson** [comment]
ah... yes. Thought that it was closed by one of the commit messages.

And thanks for all of your work on this!
