### ISSUE TITLE
create example how-to book

### ISSUE THREAD

**Issue by blueheadpublishing** [worlduniting/old-bookshop#9]
Create a book built with bookshop and use as the book-source generated with 'bookshop new' so users have a ready-made example of a bookshop-built book.

Book should:
1. Demonstrate a basic book structure
2. Provide examples of CSS styling
3. Provide best-practice guidelines for book development/publishing
4. Provide recipes for more complicated elements (e.g. table of contents, indexes, sidebars, graphics layout)
5. Provide more detail around the boom-microformat

**Comment by blueheadpublishing** [comment]
Consider adding appendix on Adobe Javascript

http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/Acro6JSGuide.pdf

**Comment by davidandrewthompson** [comment]
removing this from the issue list and offlining it to BlueHead Publishing's timeline.
